
CREATE Table Personel (
PersonelID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
Ad NVARCHAR(50) NOT NULL,
SoYAD NVARCHAR(50) NOT NULL,
Pozisyon NVARCHAR(100) NOT NULL,
BaslangicTarihi DATE NOT NULL

);
CREATE TABLE Maaslar(
MAASID INT NOT NULL IDENTITY(1,1),
PersonelID INT,
FOREIGN KEY (PersonelID ) REFERENCES Personel(PersonelID),
MaasMiktari BIGINT NOT NULL,
GüncellemeTarihi DATE NOT NULL
);