
CREATE TABLE Kulüpler(
KulüpID INT PRIMARY KEY IDENTITY(1,1) NOT NULL CHECK (KulüpID BETWEEN 1 AND 5),
KulüpAdi NVARCHAR(100) NOT NULL,
KurulusYili INT NOT NULL

);

CREATE TABLE OgrenciKulüp(
OgrenciID INT PRIMARY KEY IDENTITY(1,1) NOT NULL CHECK (OgrenciID BETWEEN 1 AND 20),
KulüpID INT,

FOREIGN KEY(KulüpID) REFERENCES Kulüpler(KulüpID),
AdSoyad NVARCHAR(50) NOT NULL,
Rol NVARCHAR(100) NOT NULL

);